[package]
name = "rtf-config"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
futures.workspace = true
indoc.workspace = true
itertools.workspace = true
rtf-core = { path = "../rtf-core" }
rtf-derive = { path = "../rtf-derive" }
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
strum.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
reqwest.workspace = true
schemars.workspace = true

[dev-dependencies]
assert_fs.workspace = true
pretty_assertions.workspace = true
simple_test_case.workspace = true
simple_txtar.workspace = true
tokio.workspace = true
