[package]
name = "rtf-config"
version.workspace = true
edition.workspace = true

[dependencies]
futures.workspace = true
jsonschema = { version = "0.30.0", default-features = false, features = ["resolve-file"] }
rtf-core = { path = "../rtf-core" }
serde.workspace = true
serde_json.workspace = true
serde_yaml = "0.9.34"
strum.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
simple_test_case.workspace = true
simple_txtar.workspace = true
tokio.workspace = true
rtf-test-utils = { path = "../rtf-test-utils" }
