[package]
name = "rtf-config"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
bytes.workspace = true
humantime.workspace = true
indoc.workspace = true
itertools.workspace = true
promql-parser.workspace = true
regex = "1.13.1"
reqwest.workspace = true
rtf-derive = { path = "../rtf-derive" }
rtf-integrations = { path = "../rtf-integrations" }
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
strum.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
assert_fs.workspace = true
predicates.workspace = true
pretty_assertions.workspace = true
simple_test_case.workspace = true
tokio.workspace = true
