{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rep-orchestrator.fullname" . }}
  labels:
    {{- include "rep-orchestrator.labels" . | nindent 4 }}
type: Opaque
stringData:
  apollo-key: {{ .Values.config.apolloKey | quote }}
  github-app-id: {{ .Values.github.appId | quote }}
  {{- if .Values.db.password.enabled }}
  db-pass: {{ .Values.db.password.value | quote }}
  {{- end }}
{{- end }}
