apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rep-orchestrator.fullname" . }}
  labels:
    {{- include "rep-orchestrator.labels" . | nindent 4 }}
type: Opaque
stringData:
  apollo-key: {{ .Values.config.apolloKey | quote }}
  github-token: {{ .Values.config.githubToken | quote }}
  db-pass: {{ .Values.db.pass | quote }}
