apiVersion: v1
kind: Service
metadata:
  name: {{ include "rep-orchestrator.fullname" . }}
  labels:
    {{- include "rep-orchestrator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "rep-orchestrator.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
