apiVersion: batch/v1
kind: Job
metadata:
  name: scenario-execution
  namespace: demo-namespace
  labels:
    rtf.io/execution-id: "1234"
spec:
  backoffLimit: 0  # Don't retry failed scenarios
  ttlSecondsAfterFinished: 3600  # Cleanup after 1 hour
  template:
    metadata:
      labels:
        rtf.io/execution-id: "1234"
    spec:
      restartPolicy: Never

      initContainers:
        - name: rtf-resolve
          image: us-central1-docker.pkg.dev/platform-cross-environment/platform-docker/rtf-toolbox:edge
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e

              echo "Resolving scenario..."
              rtf resolve scenario /scenario/scenario.yaml --outdir /shared/providers

              echo "Writing out run script..."
              cat << EOF > /shared/run.sh
              #!/bin/sh

              trap 'touch /shared/scenario-exited' EXIT
              echo "Exit trap installed"

              echo "Sourcing RTF env vars"
              . /shared/providers/scenario.env

              export OUTDIR=/shared/output
              export RTF_OUTPUT="\$OUTDIR/RTF_OUTPUT"

              mkdir -p /shared/output

              echo "Running test scenario"
              { sh \$SMOKE_SCRIPT 2>&1; echo $? > /shared/scenario_exit_status; } |
                tee /shared/output/output.log
              EOF

              chmod -R 777 /shared/run.sh

              ls -laR /shared/providers/
          volumeMounts:
            - name: scenario-config
              mountPath: /scenario
              readOnly: true
            - name: shared
              mountPath: /shared

      containers:
        - name: scenario-runner
          image: ghcr.io/modelcontextprotocol/inspector # from scenario.yaml
          command: ["/bin/sh", "-c", "/shared/run.sh"]
          workingDir: /shared
          volumeMounts:
            - name: shared
              mountPath: /shared
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sync"]  # Ensure writes are flushed

        - name: output-collector
          image: us-central1-docker.pkg.dev/platform-cross-environment/platform-docker/rtf-toolbox:edge
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for scenario to complete..."
              while [ ! -f /shared/scenario-exited ]; do
                sleep 5
              done

              echo "Scenario finished. Showing output..."
              ls -laR /shared/
              cat /shared/output/output.log

          volumeMounts:
            - name: shared
              mountPath: /shared
              readOnly: true

      volumes:
        - name: scenario-config
          configMap:
            name: "rtf-scenario-config"
        - name: shared
          emptyDir: {}
