{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "rtf-orchestrator.fullname" . }}
  namespace: cluster-api
  labels:
    {{- include "rtf-orchestrator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rtf-orchestrator.fullname" . }}
  namespace: cluster-api
  labels:
    {{- include "rtf-orchestrator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rtf-orchestrator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "rtf-orchestrator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
