{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtf-orchestrator.fullname" . }}
  labels:
    {{- include "rtf-orchestrator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rtf-orchestrator.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
{{- end }}
