image:
  repository: rtf-orchestrator
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  nodePort: 30035

config:
  logLevel: "info,hyper=error,rtf_orchestrator=debug"

secrets:
  apolloKey:
    name: "rtf-orchestrator"
  githubAppId:
    name: "rtf-orchestrator"
  githubPrivateKey:
    name: "github-app-private-key"
  dbPassword:
    name: "rtf-orchestrator"

db:
  password: password

k8s:
  workloadClusters:
    - name: alpha
      kubeconfigSecretRef:
        name: "orchestrator-kubeconfig"
        key: "value"

configMaps:
  admins: "orchestrator-admins"
  config: "orchestrator-config"
