query GetSubgraphSDL($serviceId: ID!, $name: String!, $from: Timestamp!, $to: Timestamp!, $filter: OperationInsightsListFilterInput, $first: Int) {
  service(id: $serviceId) {
    variant(name: $name) {
      id
      byRequests: operationInsightsList(from: $from, to: $to, filter: $filter, first: $first) {
        nodes {
          id
          displayName
          type
          requestCountPerMin
        }
      }
    }
  }
} 
{
  "from": "-86400",
  "to": "-0",
  "filter": {
    "or": []
  },
  "serviceId": "",
  "name": "prod",
  "first": 5
}