[package]
name = "rtf-cli"
version.workspace = true
edition.workspace = true

[[bin]]
doc = false
name = "rtf"
path = "src/main.rs"

[dependencies]
rep-orchestrator-shared = { path = "../rep-orchestrator-shared" }
rtf-cli-shared = { path = "../rtf-cli-shared" }
rtf-config = { path = "../rtf-config" }
rtf-core = { path = "../rtf-core" }
rtf-integrations = { path = "../rtf-integrations" }

anyhow.workspace = true 
assert_fs.workspace = true
clap_complete = "4.6.2"
clap.workspace = true
git-version.workspace = true
open.workspace = true
reqwest.workspace = true
schemars.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
serde.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
indoc.workspace = true
predicates.workspace = true
simple_test_case.workspace = true
walkdir = "2.5.0"

[build-dependencies]
clap-markdown = "0.1.5"
clap_complete = "4.6.2"
clap.workspace = true
reqwest.workspace = true
