[package]
name = "rtf-cli"
version.workspace = true
edition.workspace = true

[[bin]]
doc = false
name = "rtf"
path = "src/main.rs"

[dependencies]
rtf-config = { path = "../rtf-config" }
rtf-core = { path = "../rtf-core" }
rtf-integrations = { path = "../rtf-integrations" }

anyhow.workspace = true 
assert_fs.workspace = true
clap.workspace = true
clap_complete = "4.5.66"
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
indoc.workspace = true
predicates.workspace = true
simple_test_case.workspace = true
walkdir = "2.5.0"

[build-dependencies]
rtf-config = { path = "../rtf-config" }

clap-markdown = "0.1.5"
clap_complete = "4.5.66"
clap.workspace = true
