[package]
name = "rtf-cli"
version.workspace = true
edition.workspace = true

[[bin]]
doc = false
name = "rtf"
path = "src/main.rs"

[dependencies]
rtf-config = { path = "../rtf-config" }
rtf-core = { path = "../rtf-core" }

anyhow.workspace = true 
clap = { version = "4.5.47", features = ["derive"] }
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
assert_fs.workspace = true
predicates.workspace = true
simple_test_case.workspace = true

[build-dependencies]
rtf-config = { path = "../rtf-config" }

clap-markdown = "0.1.5"
clap_complete = "4.5.57"
clap = { version = "4.5.47", features = ["derive"] }
schemars.workspace = true
serde_json.workspace = true
