apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kompose-output.yaml
patches:
  - target:
      kind: Deployment
      annotationSelector: "rtf.io/file-providers=true"
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: placeholder  # overridden by target selector
      spec:
        template:
          spec:
            initContainers:
              - name: toolbox-init
                image: us-central1-docker.pkg.dev/platform-cross-environment/apollo-private-docker/rtf-toolbox:edge
                imagePullPolicy: __IMAGE_PULL_POLICY__
                command:
                  - rep-orchestrator-cli
                  - resolve-environment
                  - --outdir
                  - __OUTDIR__
                env:
                  - name: APOLLO_REP_ORCHESTRATOR_URL
                    value: __ORCHESTRATOR_URL__
                  - name: APOLLO_REP_ORCHESTRATOR_EXECUTION_ID
                    value: __EXECUTION_ID__
                  - name: APOLLO_REP_ORCHESTRATOR_EXECUTION_TOKEN
                    value: __EXECUTION_TOKEN__
                volumeMounts:
                  - mountPath: __OUTDIR__
                    name: providers
  - target:
      kind: Deployment
      annotationSelector: "rtf.io/log-collection=true"
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: placeholder  # overridden by target selector
      spec:
        template:
          metadata:
            labels:
              rtf.io/log-collection: "true"
