services:
  orchestrator:
    container_name: orchestrator
    build:
      dockerfile: ./docker/local/Dockerfile
      context: ../
    entrypoint: "cargo watch -i 'tests/**' -x run"
    ports:
      - 8035:8035
    environment:
      CARGO_TARGET_DIR: "/target"
      RUST_LOG: "info,rep_orchestrator=debug,hyper=error"
      RTF_HOST: "0.0.0.0"
      RTF_PORT: "8035"
      RTF_DB_HOST: "db"
      RTF_DB_PORT: "5432"
      RTF_DB_NAME: "rtf_rep"
      RTF_DB_USER: "service_user"
      RTF_DB_PASS: "password"
      RTF_APOLLO_KEY: "dummy"
      RTF_GITHUB_TOKEN: "dummy"
    volumes:
      - ../../../:/runtime-testing-framework
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/target
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8035/health"]
      interval: 5s
      retries: 50
    depends_on:
      - db

  db:
    container_name: db
    build: ./db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "@1234"
      PGPASSWORD: "@1234"
      SERVICE_USER: "service_user"
      SERVICE_PASSWORD: "password"
      DB_NAME: "rtf_rep"

volumes:
  cargo-cache: null
  target-cache: null
