services:
  nginx:
    image: nginx:alpine
    labels:
      rtf.io/file-providers: true
    command: sh -c "nginx -c ${NGINX_CONF_FILE} -g 'daemon off;'"
    pull_policy: always

volumes:
  providers:
    driver: local
