image:
  repository: rep-orchestrator
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  nodePort: 30035

gcs:
  bucket: "rtf-local"
  # mockUrl and config.orchestratorUrl are set by the Tiltfile using the mgmt cluster container IP

config:
  logLevel: "info,hyper=error,rep_orchestrator=debug"

db:
  pass: password

k8s:
  kubeconfigPath: "/root/.kube/config"
  mgmtContext: "kind-rtf-mgmt"
  workloadContext: "kind-rtf-workload"
  kubeconfigSecret: "orchestrator-kubeconfig"
