image:
  repository: rep-orchestrator
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  nodePort: 30035

gcs:
  bucket: "rtf-local"
  mockPublicUrl: "http://localhost:8080"
  # mockInternalUrl and config.orchestratorUrl are set by the Tiltfile using the mgmt cluster container IP

config:
  logLevel: "info,hyper=error,rep_orchestrator=debug"
  toolboxPullPolicy: "IfNotPresent"
  failedExecutionTtlSecs: "60"

secrets:
  apolloKey:
    name: "rep-orchestrator"
  githubAppId:
    name: "rep-orchestrator"
  githubPrivateKey:
    name: "github-app-private-key"
  dbPassword:
    name: "rep-orchestrator"

db:
  password: password

k8s:
  workload:
    context: "kind-rtf-workload"
    kubeconfigSecretRef:
      name: "orchestrator-kubeconfig"
