image:
  repository: rep-orchestrator
  tag: latest
  pullPolicy: Never

config:
  logLevel: "info,hyper=error,rep_orchestrator=debug"

db:
  pass: password

k8s:
  kubeconfigPath: "/root/.kube/config"
  mgmtContext: "kind-rtf-mgmt"
  workloadContext: "kind-rtf-workload"
  kubeconfigSecret: "orchestrator-kubeconfig"
