name: environment-sanity-check
description: "Sanity check that we template and run commands correctly in the environment"

variable_definitions:
  - name: message
    description: "A message to echo out"

setup:
  command:
    name: echo-message.sh
    kind: relative_path
    path: scripts/echo-message.sh
  env_vars:
    MESSAGE: "{{ message }}"
    STAGE: "env-setup"

teardown:
  command:
    name: echo-message.sh
    kind: relative_path
    path: scripts/echo-message.sh
  env_vars:
    MESSAGE: "{{ message }}"
    STAGE: "env-teardown"
