[package]
name = "rtf-integrations"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
apollo-compiler.workspace = true
bytes.workspace = true
chrono.workspace = true
futures.workspace = true
google-cloud-auth.workspace = true
google-cloud-secretmanager-v1.workspace = true
google-cloud-gax.workspace = true
graphql_client = "0.16.0"
itertools.workspace = true
jsonwebtoken = { version = "11.0.0", features = ["aws_lc_rs"] }
oauth2.workspace = true
open.workspace = true
rand.workspace = true
reqwest.workspace = true
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
xdg.workspace = true

[dev-dependencies]
anyhow.workspace = true
rsa = "0.10.0-rc.18"
simple_test_case.workspace = true
