[package]
name = "rtf-integrations"
version.workspace = true
edition.workspace = true

[dependencies]
apollo-compiler.workspace = true
base64 = "0.22"
bytes.workspace = true
chrono.workspace = true
futures.workspace = true
google-cloud-gax.workspace = true
google-cloud-secretmanager-v1.workspace = true
graphql_client = "0.16.0"
itertools.workspace = true
jsonwebtoken = { version = "10.3.0", features = ["rust_crypto", "use_pem"] }
oauth2.workspace = true
open.workspace = true
rand.workspace = true
reqwest.workspace = true
serde_json.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
anyhow.workspace = true
rand_core = "0.6"
rsa = "0.9"
simple_test_case.workspace = true
