# Orchestrator config file for use inside of the local Tilt stack.
#
# There are several URLs required for this configuration which only become
# known once the Tilt stack is running. As such, this file is templated by Tilt
# before being provided to the running orchestrator service. Such values are
# identified as "__PLACEHOLDER__"
apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-config
  namespace: orchestrator
data:
  config.yaml: |
    admins_path: /etc/rtf-orchestrator/admins/members

    db:
      host: postgres
      port: 5432
      name: rtf_orchestrator
      user: service_user
      pass: password

    server:
      host: 0.0.0.0
      port: 8035
      body_limit_mb: 50
      orchestrator_url: __ORCHESTRATOR_URL__

    workload_clusters:
      default_cluster: alpha
      max_queued_executions: 100
      cluster_roles:
        cluster_read: scenario-cluster-read
        namespace_read: scenario-namespace-read
        namespace_write: scenario-namespace-write
      available_clusters:
        - name: alpha
          kubeconfig_secret_name: orchestrator-kubeconfig
          workload_context: kind-rtf-workload
          execution:
            max_concurrent: 10
            failed_execution_ttl_secs: 60
            retry_window_secs: 300
            poll_interval_secs: 10
            namespace_cleanup_timeout_secs: 90

    toolbox:
      pull_policy: IfNotPresent
      image_repository: rtf-toolbox
      image_tag: edge

    otel:
      collector_grpc: http://otel-collector.monitoring:4317
      collector_http: http://otel-collector.monitoring:4318
      prometheus_endpoint: __PROMETHEUS_ENDPOINT__

    gcs:
      bucket: rtf-local
      url_ttl_secs: 300
      mock_internal_url: __MOCK_INTERNAL_GCS_URL__
      mock_public_url: http://localhost:8080/gcs
