# Test for input values being created correctly
schema @core(feature: "https://specs.apollo.dev/core/v0.1") @core(feature: "https://specs.apollo.dev/join/v0.1") @apollo_studio_metadata(buildId: "0b12a515-e79b-4e3d-bab6-6b564bc8b1e5", checkId: null, launchId: "0b12a515-e79b-4e3d-bab6-6b564bc8b1e5") {
  query: Query
}

interface Something {
    iA: String
}

type ThingA implements Something {
    iA: String
    c: Float
}

type ThingB implements Something {
    iA: String
    c: String
}

type Query{
    doSomething: Something
}
