name: router-perf-env
description: |
  Expects to be executed on a GCP VM as part of a router-scale test. This environment
  will spin up a specified build of the router along with mock subgraphs and supporting
  services. It is possible to configure the resources given to the router and subgraphs.

values:
  - name: rust_version
    description: "Rust version to use to build the router"
  - name: router_commit_ref
    description: "The git commit ref for the router build"
  - name: graph_ref
    description: "The graphos graph ref to run the router for"

setup:
  command:
    name: router-perf-setup.sh
    kind: relative_path
    path: scripts/router-perf-setup.sh

  env_vars:
    APOLLO_USAGE_REPORTING_INGRESS_URL: http://127.0.0.1:1234/studio
    APOLLO_USAGE_REPORTING_OTLP_INGRESS_URL: http://127.0.0.1:4317
    APOLLO_GRAPH_REF: "{{ graph_ref }}"

  file_providers:
    - name: install-router.sh
      env_var: ROUTER_INSTALL_SCRIPT
      kind: build_router_from_source
      rust_version: "{{ rust_version }}"
      commit_ref: "{{ router_commit_ref }}"

    - name: router-config.yaml
      env_var: ROUTER_CONFIG
      kind: required
      message: "Must provide a router config file"

    - name: supergraph.graphql
      env_var: SUPERGRAPH_SCHEMA
      kind: graphos_supergraph
      graph_ref: "{{ graph_ref }}"

    - name: subgraphs
      env_var: SUBGRAPH_DIR
      kind: graphos_subgraphs
      graph_ref: "{{ graph_ref }}"

    - name: router-cgroup.txt
      env_var: ROUTER_CGROUP_CONFIG
      kind: inline
      content: |
        ROUTER_CPU_REQ="4"
        ROUTER_MEM_REQ=""
        ROUTER_MEM_LIM="8G"

    - name: subgraph_config.txt
      env_var: SUBGRAPH_CONFIG
      kind: inline
      content: |
        SUBGRAPH_WAVEFORM=sine
        SUBGRAPH_LATENCY=5ms
        SUBGRAPH_AMPLITUDE=2ms
        SUBGRAPH_PERIOD=10s

  provides:
    - name: router_pid
      description: "The PID of the router process we started"
    - name: router_cgroup
      description: "Whether or not a cgroup was configured for the router"

teardown:
  command:
    name: router-perf-teardown.sh
    kind: relative_path
    path: scripts/router-perf-teardown.sh

  env_vars:
    ROUTER_PID: "{{ router_pid }}"
    ROUTER_CGROUP: "{{ router_cgroup }}"
    GRAPH_REF: "{{ graph_ref }}"
