//! Parsing of our command line arguments using Clap's derive API
use clap::{Parser, Subcommand};

// TODO: the hierarchy for the commands here needs to be reworked once we have defined the overall
// structure of the framework. Things should be namespaced rather than all living at the top level
// as they currently do.

// NOTE: All of the doc comments here are parsed by Clap and used to build out the documentation
// seen in the CLI. We treat them as user facing and aim to provide as much useful information as
// possible without overwhelming the user with output when they run '-h' or '--help'.
//
// This file is also pulled in to the `build.rs` of this crate so Args can be passed to
// `clap_markdown` in order to generate the `help.md` file in the root of the repo:
//   -> see https://crates.io/crates/clap-markdown for details

/// A swiss army knife for testing the Apollo Runtime.
///
/// You can set the `RUST_LOG` environment variable to alter the logging output of this tool.
#[derive(Debug, Parser)]
#[clap(about, name = "rtf", long_about = None)]
pub struct Args {
    #[clap(subcommand)]
    pub command: Command,
}

#[derive(Debug, Subcommand)]
pub enum Command {
    /// Download and resolve the config required to run a single supergraph under router-scale.
    /// The config file generated by this command is mostly a stub containing default values, to
    /// generate the full config for a router-scale test please run the 'prepare' subcommand.
    FetchSupergraph {
        /// The graph-id to download
        #[arg(long)]
        graph_id: String,
        /// The variant of `graph-id` to download
        #[arg(long)]
        variant: String,
        /// The directory to write output to
        #[arg(long, default_value = "output")]
        out_dir: String,
        /// Attempt to pull supergraph details from the staging instance of studio rather than prod
        #[arg(long, action)]
        staging: bool,
    },

    /// Pull details of the most common operations for a given supergraph from studio and generate
    /// mock request data for each one.
    TopOperations {
        /// The graph-id to find operations for
        #[arg(long)]
        graph_id: String,
        /// The variant of `graph-id` to pull operations for
        #[arg(long)]
        variant: String,
        /// The number of operations to pull
        #[arg(short, long, default_value = "20")]
        n_operations: usize,
        /// Whether or not to include mutations as part of the generated request data
        /// (The rehydrate tool used by router-scale defaults to skipping)
        #[arg(long, action)]
        skip_mutations: bool,
        /// The directory to write the generated request data to
        #[arg(long, default_value = "output")]
        out_dir: String,
        /// Attempt to pull supergraph details from the staging instance of studio rather than prod
        #[arg(long, action)]
        staging: bool,
    },
}
