name: value-not-in-allowed-values
description: |
  Check the error shown when a provided variable value is not in the allowed_values

variables:
  foo: "c"

scenario:
  inline:
    name: inline-scenario
    description: an inline scenario
    variable_definitions:
      - name: foo
        description: A variable with restricted values
        allowed_values:
          - "a"
          - "b"
    command:
      name: scenario.sh
      kind: inline
      content: |
        #!/usr/bin/env sh
        echo "test"
    env_vars:
      FOO: "{{ foo }}"

environment:
  inline:
    name: inline-environment
    description: an inline environment
    setup:
      command:
        name: setup.sh
        kind: inline
        content: |
          #!/usr/bin/env sh
          echo "setup"
    teardown:
      command:
        name: teardown.sh
        kind: inline
        content: |
          #!/usr/bin/env sh
          echo "teardown"
