schema {
    query:Query
}

enum PropertyStateEnum {
  LEAD
  LEAD_CANCELLED
  LEAD_CALL_LATER
  OPPORTUNITY_DRAFT
  OPPORTUNITY_CANCELLED
  OPPORTUNITY_SUBMITTED
}

interface House {
  houseCommon: HouseCommonFields
}

type HouseCommonFields {
    zip_code: String
}

interface Property {
    id: ID!
    salesforceId: ID
    state: PropertyStateEnum!
}

type Customer {
    properties: [Property!]!
}

type SemiDetachedHouse implements Property & House {
    id: ID!
    salesforceId: ID
    state: PropertyStateEnum!
    houseCommon: HouseCommonFields
}

union _Entity = Customer

scalar _Any

type Query {
    customer(id: ID!): Customer
    _entities(representations: [_Any!]!): [_Entity]!
}