input LanguageTagInput {
  language: String!
  script: String
}


interface Concept
{
  nsid: Nsid!
  translatedName(languageTag: LanguageTagInput): Translation 
}

type LanguageTag
{
  code: String
  language: String!
  privateUse: String
  region: String
  script: String
}

type Nsid {
  id: Int!
  ns: Int!
}

type Translation {
  languageTag: LanguageTag!
  value: String!
}

type Destination implements Concept {
    nsid: Nsid!
  translatedName(languageTag: LanguageTagInput): Translation 
  where: String
}

type AdvertiserDetails implements Concept {
  nsid: Nsid!
  translatedName(languageTag: LanguageTagInput): Translation 
}

type AccommodationDetails implements Concept{
  isVRBOOLB: Boolean! 
  nsid: Nsid!
  translatedName(languageTag: LanguageTagInput): Translation 
  typeObject: Concept!
}
