port: 8080
headers: {}

latency:
  base: 5ms
  sine:
    amplitude: 2ms
    period: 10s

response_generation:
  null_ratio: [1, 2]
  array:
    min_length: 0
    max_length: 10
  scalars:
    String:
      type: String
      min_len: 5
      max_len: 20
