[package]
name = "rep-orchestrator"
version.workspace = true
edition.workspace = true

[features]
# Used to prevent tests that need a running DB from executing unless explicitly requested
# Annotate such tests with the following:
#   #[cfg_attr(not(feature = "db_tests"), ignore)]
#
# Execute the tests using "cargo test --features db_tests"
db_tests = []

# Mark all integration tests as being DB tests.
# -> This needs to be done for each test file in /tests/
[[test]]
name = "suite"
required-features = ["db_tests"]

[dependencies]
rep-orchestrator-shared = { path = "../rep-orchestrator-shared" }
rtf-config = { path = "../rtf-config" }
rtf-core = { path = "../rtf-core" }
rtf-integrations = { path = "../rtf-integrations" }

axum = { version = "0.8.8", features = ["macros"] }
chrono.workspace = true
envy = "0.4.2"
k8s-openapi = { version = "0.27.1", features = ["schemars", "v1_35"] }
kube = { version = "3.0.1", features = ["aws-lc-rs", "derive", "runtime"] }
kube-runtime = "3.0.1"
schemars.workspace = true
serde_json.workspace = true
serde.workspace = true
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "migrate", "chrono", "json", "uuid"] }
thiserror.workspace = true
tokio-stream = "0.1.18"
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
rtf-cli = { path = "../rtf-cli" }

anyhow.workspace = true 
assert_fs.workspace = true
indoc.workspace = true
reqwest.workspace = true
serde_yaml.workspace = true
simple_test_case.workspace = true
