[package]
name = "rtf-derive"
version.workspace = true
edition.workspace = true
publish = false

[lib]
proc-macro = true

[dependencies]
darling = "0.24.1"
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = "3.0.5"

[dev-dependencies]
rtf-config = { path = "../rtf-config" }
rustversion = "1.0.23"
simple_test_case.workspace = true
trybuild = "1.0.121"
