[package]
name = "rtf-derive"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.23.0"
proc-macro2 = "1.0.106"
quote = "1.0.44"
syn = "2.0.115"

[dev-dependencies]
rtf-config = { path = "../rtf-config" }
rustversion = "1.0.22"
simple_test_case.workspace = true
trybuild = "1.0.116"
