#!/usr/bin/env bash
# Check that each chart's README.md is in sync with its values.yaml and README.md.gotmpl
# by regenerating it in a temp directory and comparing with the committed version.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DPRINT_CONFIG="$PROJECT_ROOT/dprint.json"

# Charts whose README.md is generated by helm-docs and checked here.
CHART_DIRS=(
    "$PROJECT_ROOT/crates/rep-orchestrator/helm/rep-orchestrator"
    "$PROJECT_ROOT/crates/orchestrator-ui/helm/orchestrator-ui"
)

# Check if helm-docs is available
if ! command -v helm-docs &> /dev/null; then
    echo "ERROR: helm-docs is not installed"
    exit 1
fi

# Check if dprint is available
if ! command -v dprint &> /dev/null; then
    echo "ERROR: dprint is not installed"
    exit 1
fi

check_chart() {
    local chart_dir="$1"
    local readme_file="$chart_dir/README.md"

    # Check if README.md exists
    if [[ ! -f "$readme_file" ]]; then
        echo "ERROR: README.md not found at $readme_file"
        return 1
    fi

    # Create a temporary directory
    local temp_dir
    temp_dir=$(mktemp -d)
    trap "rm -rf $temp_dir" RETURN

    # Copy the chart to the temp directory
    cp -r "$chart_dir" "$temp_dir/chart"

    # Run helm-docs on the temp copy
    helm-docs -c "$temp_dir/chart" > /dev/null 2>&1 || {
        echo "ERROR: helm-docs failed for $chart_dir"
        return 1
    }

    # Format the generated README with dprint to match the committed version's formatting.
    # Use --stdin because dprint applies its config's includes/excludes (rooted at the project)
    # and won't format files outside the project tree.
    local formatted_readme="$temp_dir/chart/README.formatted.md"
    dprint fmt --stdin README.md --config "$DPRINT_CONFIG" \
        < "$temp_dir/chart/README.md" > "$formatted_readme" || {
        echo "ERROR: dprint fmt failed for $chart_dir"
        return 1
    }
    mv "$formatted_readme" "$temp_dir/chart/README.md"

    # Compare the generated README.md with the committed version
    if diff -u "$readme_file" "$temp_dir/chart/README.md" > /dev/null 2>&1; then
        echo "✓ $(basename "$chart_dir") README.md is in sync with values.yaml"
        return 0
    else
        echo "ERROR: $(basename "$chart_dir") README.md is out of sync with values.yaml"
        echo ""
        echo "Run 'mise generate-helm-docs' to regenerate README.md"
        echo ""
        diff -u "$readme_file" "$temp_dir/chart/README.md" || true
        return 1
    fi
}

status=0
for chart_dir in "${CHART_DIRS[@]}"; do
    check_chart "$chart_dir" || status=1
done
exit "$status"
