//! The integrations with external APIs for the Apollo Runtime Testing Framework.
#![warn(
    clippy::complexity,
    clippy::correctness,
    clippy::style,
    future_incompatible,
    missing_debug_implementations,
    missing_docs,
    rust_2018_idioms,
    rustdoc::all
)]
#![deny(clippy::undocumented_unsafe_blocks)]

use bytes::Bytes;
use github::GithubClient;
use reqwest::{Error, StatusCode};
use std::future::Future;

pub mod github;
pub mod graphos;
pub mod iap;

use graphos::{
    PlatformClient,
    platform_query::{PROD_STUDIO_URL, STAGING_STUDIO_URL},
};

/// The environment variable name for the api key used to authenticate with the GraphOS API
pub const APOLLO_KEY_ENV_VAR: &str = "APOLLO_KEY";
/// The environment variable name for setting the apollo-sudo=true header in GraphOS API requests
pub const APOLLO_SUDO_ENV_VAR: &str = "APOLLO_SUDO";
/// The environment variable name for whether or not to use the staging GraphOS API
pub const GRAPH_OS_STAGING_ENV_VAR: &str = "GRAPHOS_STAGING";
/// The maximum number of queries to run in parallel querying the platform API.
pub const N_PARALLEL_FETCH: usize = 20;
/// The environment variable name for the api token used to authenticate with the GitHub API.
pub const GITHUB_TOKEN_ENV_VAR: &str = "GITHUB_TOKEN";

/// A client implementation that is backed by a [reqwest::Client].
#[derive(Debug, Default, Clone)]
pub struct ReqwestClient {
    pub(crate) inner: reqwest::Client,
    pub(crate) github: Option<GithubClient>,
    pub(crate) platform: Option<PlatformClient>,
}

impl ReqwestClient {
    /// Construct a new [ReqwestClient]
    pub fn new() -> Self {
        Self {
            inner: reqwest::Client::new(),
            github: None,
            platform: None,
        }
    }

    /// Obtain a reference to an API client for running operations with the Apollo platform API if
    /// config is available.
    pub fn platform_client(&self) -> Option<&PlatformClient> {
        self.platform.as_ref()
    }

    /// Obtain a reference to an API client for making requests to the GitHub REST API if config is
    /// available.
    pub fn github_client(&self) -> Option<&GithubClient> {
        self.github.as_ref()
    }

    /// Provide configuration for making requests to the Apollo platform API.
    pub fn with_platform_config(
        &mut self,
        api_key: impl Into<String>,
        staging: bool,
        sudo: bool,
    ) -> &mut Self {
        let url = if staging {
            STAGING_STUDIO_URL
        } else {
            PROD_STUDIO_URL
        };

        self.platform = Some(PlatformClient {
            inner: self.inner.clone(),
            url: url.into(),
            api_key: api_key.into().into(),
            sudo,
        });

        self
    }

    /// Provide configuration for GitHub App installation authentication.
    ///
    /// `private_key_pem` must be the PKCS#1 PEM private key generated by GitHub
    /// ("BEGIN RSA PRIVATE KEY"). Installation IDs are discovered per-org on first use; access
    /// tokens are cached and refreshed automatically.
    pub fn with_github_app_config(
        &mut self,
        app_id: u64,
        private_key_pem: impl Into<String>,
    ) -> &mut Self {
        self.github = Some(GithubClient::new_from_app(app_id, private_key_pem));
        self
    }

    /// Provide configuration for making requests to the GitHub REST API.
    pub fn with_github_config(&mut self, api_token: impl Into<String>) -> &mut Self {
        self.github = Some(GithubClient::from_shared_client(
            self.inner.clone(),
            api_token,
        ));

        self
    }
}

/// Represents the result of an HTTP request made by an `HttpClient`.
///
/// Contains the HTTP status code and the raw response body as bytes.
#[derive(Debug, Clone)]
pub struct HttpResponse {
    /// The HTTP status code returned by the server (e.g., 200 OK, 404 Not Found).
    pub status: StatusCode,

    /// The raw response body returned by the server, as bytes.
    ///
    /// This may contain any type of content (JSON, text, binary, etc.),
    /// and should be interpreted by the caller as needed.
    pub body: Bytes,
}

/// Types that implement HttpClient may be used to perform http requests
pub trait HttpClient: Send + Sync {
    /// Sends an HTTP GET request to the given `url` and returns the full response.
    ///
    /// This method performs no automatic error handling or status code validation;
    /// callers are responsible for interpreting the response body, including parsing
    /// it as JSON or text if desired, and handling any HTTP status errors.
    fn get(&self, url: &str) -> impl Future<Output = Result<HttpResponse, Error>> + Send;
}

impl HttpClient for ReqwestClient {
    async fn get(&self, url: &str) -> Result<HttpResponse, Error> {
        let response = self.inner.get(url).send().await?;
        Ok(HttpResponse {
            status: response.status(),
            body: response.bytes().await?,
        })
    }
}
