//! Smoke test for GitHub App authentication against the real GitHub API.
//!
//! Usage:
//! ```
//! GITHUB_APP_ID=<id> \
//! GITHUB_APP_PRIVATE_KEY_PATH=<path/to/private-key.pem> \
//! cargo run -p rtf-integrations --example github-app-auth
//! ```
//!
//! The private key must be the PKCS#1 PEM file generated by GitHub
//! ("BEGIN RSA PRIVATE KEY").
use rtf_integrations::github::{Client, GithubClient};
use std::{env, fs};

#[tokio::main]
async fn main() {
    let app_id: u64 = env::var("GITHUB_APP_ID")
        .expect("GITHUB_APP_ID must be set")
        .parse()
        .expect("GITHUB_APP_ID must be a number");

    let key_path =
        env::var("GITHUB_APP_PRIVATE_KEY_PATH").expect("GITHUB_APP_PRIVATE_KEY_PATH must be set");
    let private_key_pem = fs::read_to_string(&key_path).expect("failed to read private key file");

    let client = GithubClient::new_from_app(app_id, private_key_pem);

    let org = "apollographql";
    let repo = "runtime-testing-framework";
    let file = "README.md";
    let git_ref: Option<&str> = None;

    println!("authenticating as GitHub App {app_id}");
    println!("fetching {org}/{repo}/{file} ...");

    let content = client
        .string_file_content(org, repo, file, git_ref)
        .await
        .expect("failed to fetch file");

    println!("ok — got {} bytes", content.len());
}
