[book]
authors = ["Runtime Readiness"]
language = "en"
multilingual = false
src = "src"
title = "Runtime Testing Framework"

[output.html]
git-repository-url = "https://github.com/apollographql/runtime-testing-framework"

[output.html.playpen]
editable = true
editor = "ace"

[output.html.fold]
enable = true
