[book]
authors = ["Runtime Readiness"]
language = "en"
src = "src"
title = "Runtime Testing Framework"

[output.html]
git-repository-url = "https://github.com/apollographql/runtime-testing-framework"

[output.html.playpen]
editable = true

[output.html.fold]
enable = true
level = 0         # the depth to start folding
