name: docker-compose-inline-dir
description: Test that InlineDir compose file provider works with multiple compose files

variables:
  message: "hello from inline dir"

scenario:
  from:
    kind: local
    relative_path: scenario.yaml

environment:
  from:
    kind: local
    relative_path: environment.yaml
