name: Check Platform API Supergraph Schema

on:
  schedule:
    - cron: '0 0 * * *' # Run every day
  workflow_dispatch: { } # support manual triggering as well

jobs:
  check_schema:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Check for schema changes
        id: check_schema
        run: |
          echo ":: Pulling current apollo-platform schema..."
          # shellcheck disable=SC2016
          QUERY='query FetchSchema($fetchDocument: Boolean!) {
            graph(id: "apollo-platform") {
              variant(name: "main") {
                latestPublication {
                  schema {
                    document @include(if: $fetchDocument)
                  }
                }
              }
            }
          }'
          DATA=$(jq -n --arg query "$QUERY" '{ "variables": { "fetchDocument": true }, "query": $query }')
          curl -s \
            -H "content-type: application/json" \
            -H "apollographql-client-name: operator-schema-check" \
            -H "apollographql-client-version: 0.0.1" \
            -d "$DATA" \
            "https://api.apollographql.com/api/graphql" |
              jq -r '.data.graph.variant.latestPublication.schema.document' > "current-schema.graphql"

          REPO_ROOT="$(git rev-parse --show-toplevel)"
          SCHEMA_PATH="$REPO_ROOT/crates/rtf-core/resources/engine-prod-schema.graphql"
          # -b to ignore whitespace changes
          DIFF="$(diff -b "current-schema.graphql" "$SCHEMA_PATH" || true)"

          if [[ -n "$DIFF" ]]; then
            echo ":: In-repo schema is out of date an needs to be updated. Raising PR"
            echo "$DIFF"
            mv "current-schema.graphql" "$SCHEMA_PATH"
            echo "raise-pr=true" >> "$GITHUB_OUTPUT"
            echo "branch=update-schema/$(date +%F)" >> "$GITHUB_OUTPUT"
          else
            echo ":: In-repo schema is up to date."
            rm current-schema.graphql
            echo "raise-pr=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        if: ${{ steps.check_schema.outputs.raise-pr == 'true' }}
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e  # v7.0.8
        with:
          commit-message: 'chore: Update platform API supergraph schema'
          branch: automation/platform-schema-update
          title: 'Update apollo-platform schema'
          body: Automated PR for updating the in-repo copy of the apollo-platform schema
