name: Publish RTF Toolbox Docker Image

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/publish-rtf-toolbox.yaml"
      - "crates/**"
      - "Cargo.lock"
      - "Cargo.toml"
      - "toolbox/**"

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  publish-toolbox:
    name: Build and publish RTF toolbox image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: apollographql/release-tooling/build-and-publish@fc0d6bc05ee3f27d67aca21dc238e3926e9132e8
        with:
          context: ${{ github.workspace }}
          dockerfile_location: ${{ github.workspace }}/toolbox/Dockerfile
          image_description: "RTF toolbox image with rtf binary and supporting tools for use in CI and REP"
          image_name: rtf-toolbox
          platforms: linux/amd64,linux/arm64
