name: Update GitHub pages site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2

      - name: Build
        run: mdbook build docs && cargo doc --workspace --no-deps && mv target/doc docs/book/rustdoc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
