name: Publish RTF Toolbox Docker Image

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/publish-rtf-toolbox.yaml"
      - "crates/**"
      - "Cargo.lock"
      - "Cargo.toml"
      - "toolbox/**"

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  publish-toolbox:
    name: Build and publish RTF toolbox image
    uses: apollographql/release-tooling/.github/workflows/build_and_publish.yml@a46e497cc5bed75d0b5d0bddd7822f2c14528d38
    permissions:
      contents: read
      id-token: write
    with:
      image_name: rtf-toolbox
      image_description: "RTF toolbox image with rtf binary and supporting tools for use in CI and REP"
      platforms: '[{"platform":"linux/amd64","runner":"ubuntu-24.04"},{"platform":"linux/arm64","runner":"ubuntu-24.04-arm"}]'
      context: .
      dockerfile_location: toolbox/Dockerfile
    secrets: inherit

  validate-image:
    name: Validate the new toolbox image works by running the rtf-run-test-plan action
    runs-on: ubuntu-latest
    needs: publish-toolbox
    steps:
      - uses: actions/checkout@v4

      - uses: apollographql/release-tooling/rtf-run-test-plan@a46e497cc5bed75d0b5d0bddd7822f2c14528d38
        with:
          test_plan_path: crates/rtf-cli/resources/test-plans/valid/docker-compose-environment/test-plan.yaml
          verbose: true
