name: Test RTF Run Action

on: workflow_dispatch

jobs:
  run-sanity-check:
    name: Run sanity check test plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: apollographql/release-tooling/rtf-run-test-plan@a46e497cc5bed75d0b5d0bddd7822f2c14528d38
        with:
          test_plan_path: crates/rtf-cli/resources/test-plans/valid/sanity-check/test-plan.yaml
