name: Test RTF Run Action

on: workflow_dispatch

jobs:
  run-sanity-check:
    name: Run sanity check test plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: apollographql/release-tooling/rtf-run-test-plan@91551f996e38a3d64e31d47d961bc5913da38e68
        with:
          test_plan_path: crates/rtf-cli/resources/test-plans/valid/sanity-check/test-plan.yaml
