name: Test RTF Orchestrator Run Action

on: workflow_dispatch

jobs:
  run-sanity-check:
    name: Run sanity check test plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: apollographql/release-tooling/rtf-orchestrator-run@5578f93e8a85bab43f372d520bc2ed6b8945d7e3
        with:
          test_plan_path: crates/rtf-orchestrator/resources/test-plans/valid/smoke/test-plan.yaml
          verbose: true
