name: Test RTF Run Action

on: workflow_dispatch

jobs:
  run-sanity-check:
    name: Run sanity check test plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: apollographql/release-tooling/rtf-run-test-plan@cc8018036a3df0bfb7dd8b5d92ff23c998a59579
        with:
          test_plan_path: crates/rtf-cli/resources/test-plans/valid/docker-all/test-plan.yaml
          verbose: true
