[tasks.fix-spelling]
run = "typos --write-changes"
dir = "../../"

[tasks.format-markdown]
run = "dprint fmt"
# This changes the working directory for format-markdown to the project root
dir = "../../"

[tasks.generate-docs]
run = "$(git rev-parse --show-toplevel)/scripts/generate-docs.sh"

[tasks.pr-all]
run = [
    "mise run pr-format",
    "mise run pr-clippy",
    "mise run pr-rustdoc",
    "mise run pr-spell-check",
    "mise run pr-markdown",
    "mise run pr-doc-types",
    "mise run pr-test"
]

[tasks.pr-clippy]
run = "cargo pr-clippy"

[tasks.pr-doc-types]
run = "$(git rev-parse --show-toplevel)/scripts/check-doc-types.sh"
description = "Check documentation diataxis types"

[tasks.pr-rustdoc]
run = "RUSTDOCFLAGS=\"-D warnings -D rustdoc::broken-intra-doc-links\" cargo doc --all-features --workspace --no-deps"

[tasks.pr-format]
run = "cargo pr-format"

[tasks.pr-markdown]
run = "dprint check"
# This changes the working directory for pr-markdown to the project root
dir = "../../"

[tasks.pr-spell-check]
run = "typos"
dir = "../../"

[tasks.pr-test]
run = "cargo test"

[tools]
"cargo:cargo-expand" = "1.0.119"
"cargo:cargo-llvm-cov" = "0.8.2"
"cargo:typos-cli" = "1.42.3"
dprint = "0.51.1"
mdbook = "0.5.2"
rust = "1.94.0"

[env]
_.file = '../../.env'
